name: "Rebuild Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-22.04
    steps:
      - name: Download source code
        id: down
        run: |
          git clone --depth 1 https://github.com/h1kari-715/elish-armbian-build.git

      - name: Compile Armbian
        id: compile
        run: |
          # Compile method and parameter description: https://docs.armbian.com/Developer-Guide_Build-Options
          sudo apt update && sudo apt upgrade -y
          cd elish-armbian-build/
          sudo chmod +x compile.sh
          sudo ./compile.sh build \
                   BRANCH=current \
                   BUILD_DESKTOP=yes \
                   BUILD_MINIMAL=no \
                   DESKTOP_ENVIRONMENT=kde-plasma \
                   DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base \
                   KERNEL_CONFIGURE=no \
                   RELEASE=trixie \
                   BOARD=xiaomi-elish \
                   EXPERT=yes \
                   DESKTOP_APPGROUPS_SELECTED=no 
          echo "::set-output name=status::success"
      - name: Upload Armbian Firmware to Release
        uses: ncipollo/release-action@main
        if: steps.build.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
        with:
          tag: Armbian_${{ env.FILE_DATE }}
          artifacts: ${{ env.FILEPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            This is Armbian firmware for Xiaomi Pad 5 Pro (elish)
            * Firmware information
            Default username: root
            Default password: 1234
