name: "Build Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - uses: h1kari-715/elish-armbian-build@main
        with:
          armbian_token:     "${{ secrets.GITHUB_TOKEN }}"    # GitHub token
          armbian_release:   "trixie"                         # userspace
          armbian_target:    "build"                          # build=image, kernel=kernel
          armbian_board:     "xiaomi-elish"                   # build target
          armbian_ui:        "kde-plasma"                     # build desktop
          
