name: "Rebuild Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
       - name: Download source code
        id: down
        run: |
          git clone --depth 1 https://github.com/h1kari-715/elish-armbian-build.git

      - name: Compile Armbian
        id: compile
        run: |
          # Compile method and parameter description: https://docs.armbian.com/Developer-Guide_Build-Options
          cd build/
          sudo chmod +x compile.sh
          sudo ./compile.sh build \
                   BRANCH=current \
                   BUILD_DESKTOP=yes \
                   BUILD_MINIMAL=no \
                   DESKTOP_ENVIRONMENT=kde-plasma \
                   DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base \
                   KERNEL_CONFIGURE=no \
                   RELEASE=trixie \
                   BOARD=xiaomi-elish
